sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py,codecov-travis
    - python: 3.5
      env: TOXENV=py,codecov-travis
    - python: 3.4
      env: TOXENV=py,codecov-travis
    - python: 2.7
      env: TOXENV=py,codecov-travis
    - python: 3.6
      env: TOXENV=py-pythran,codecov-travis
    - python: 2.7
      env: TOXENV=py-pythran,codecov-travis

cache: pip

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9
            - libfftw3-dev
            - libhdf5-openmpi-dev
            - openmpi-bin
            - libopenblas-dev

install:
    - pip install -U pip setuptools wheel six
    - pip install -U tox

before_script:
    - |
      mkdir -p $HOME/.config/matplotlib
      echo 'backend      : agg' > $HOME/.config/matplotlib/matplotlibrc

script:
    - tox

notifications:
  email: false
  irc: "chat.freenode.net#fluiddyn"
