name: ci-linux

on:
  - push

env:
  FORCE_COLOR: 1

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install apt packages
      run: |
        sudo apt-get update
        sudo apt-get install xvfb x11-utils libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 xdotool

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: "requirements/test.txt"

    - name: Verify Python environment
      run: |
        pip list
        pip cache list
        pip check

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip nox

    - name: Run tests
      run: |
        xvfb-run --auto-servernum nox --session tests-cov -- -v --cov-report=xml

    - name: Upload coverage to codecov
      if: ${{ success() }}
      uses: codecov/codecov-action@v3
